# Generated by Django 2.1.7 on 2019-02-24 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pothole_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='potholeinfo',
            old_name='userFeedback',
            new_name='user_feedback',
        ),
    ]
